spring.application.name=tarot
spring.ai.openai.api-key=api-key
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=5000
spring.data.redis.lettuce.pool.max-wait=10000