package com.janning_owns_it.tarot.model;

import java.util.Map;

public class Deck {

    Map<Integer, String> cards = Map.ofEntries(
            // Major Arcana
            Map.entry(0, "The Fool - Major Arcana"),
            Map.entry(1, "The Fool - Major Arcana (Reversed)"),
            Map.entry(2, "The Magician - Major Arcana"),
            Map.entry(3, "The Magician - Major Arcana (Reversed)"),
            Map.entry(4, "The High Priestess - Major Arcana"),
            Map.entry(5, "The High Priestess - Major Arcana (Reversed)"),
            Map.entry(6, "The Empress - Major Arcana"),
            Map.entry(7, "The Empress - Major Arcana (Reversed)"),
            Map.entry(8, "The Emperor - Major Arcana"),
            Map.entry(9, "The Emperor - Major Arcana (Reversed)"),
            Map.entry(10, "The Hierophant - Major Arcana"),
            Map.entry(11, "The Hierophant - Major Arcana (Reversed)"),
            Map.entry(12, "The Lovers - Major Arcana"),
            Map.entry(13, "The Lovers - Major Arcana (Reversed)"),
            Map.entry(14, "The Chariot - Major Arcana"),
            Map.entry(15, "The Chariot - Major Arcana (Reversed)"),
            Map.entry(16, "Strength - Major Arcana"),
            Map.entry(17, "Strength - Major Arcana (Reversed)"),
            Map.entry(18, "The Hermit - Major Arcana"),
            Map.entry(19, "The Hermit - Major Arcana (Reversed)"),
            Map.entry(20, "Wheel of Fortune - Major Arcana"),
            Map.entry(21, "Wheel of Fortune - Major Arcana (Reversed)"),
            Map.entry(22, "Justice - Major Arcana"),
            Map.entry(23, "Justice - Major Arcana (Reversed)"),
            Map.entry(24, "The Hanged Man - Major Arcana"),
            Map.entry(25, "The Hanged Man - Major Arcana (Reversed)"),
            Map.entry(26, "Death - Major Arcana"),
            Map.entry(27, "Death - Major Arcana (Reversed)"),
            Map.entry(28, "Temperance - Major Arcana"),
            Map.entry(29, "Temperance - Major Arcana (Reversed)"),
            Map.entry(30, "The Devil - Major Arcana"),
            Map.entry(31, "The Devil - Major Arcana (Reversed)"),
            Map.entry(32, "The Tower - Major Arcana"),
            Map.entry(33, "The Tower - Major Arcana (Reversed)"),
            Map.entry(34, "The Star - Major Arcana"),
            Map.entry(35, "The Star - Major Arcana (Reversed)"),
            Map.entry(36, "The Moon - Major Arcana"),
            Map.entry(37, "The Moon - Major Arcana (Reversed)"),
            Map.entry(38, "The Sun - Major Arcana"),
            Map.entry(39, "The Sun - Major Arcana (Reversed)"),
            Map.entry(40, "Judgement - Major Arcana"),
            Map.entry(41, "Judgement - Major Arcana (Reversed)"),
            Map.entry(42, "The World - Major Arcana"),
            Map.entry(43, "The World - Major Arcana (Reversed)"),

            // Minor Arcana - Cups
            Map.entry(44, "Ace of Cups - Minor Arcana"),
            Map.entry(45, "Ace of Cups - Minor Arcana (Reversed)"),
            Map.entry(46, "2 of Cups - Minor Arcana"),
            Map.entry(47, "2 of Cups - Minor Arcana (Reversed)"),
            Map.entry(48, "3 of Cups - Minor Arcana"),
            Map.entry(49, "3 of Cups - Minor Arcana (Reversed)"),
            Map.entry(50, "4 of Cups - Minor Arcana"),
            Map.entry(51, "4 of Cups - Minor Arcana (Reversed)"),
            Map.entry(52, "5 of Cups - Minor Arcana"),
            Map.entry(53, "5 of Cups - Minor Arcana (Reversed)"),
            Map.entry(54, "6 of Cups - Minor Arcana"),
            Map.entry(55, "6 of Cups - Minor Arcana (Reversed)"),
            Map.entry(56, "7 of Cups - Minor Arcana"),
            Map.entry(57, "7 of Cups - Minor Arcana (Reversed)"),
            Map.entry(58, "8 of Cups - Minor Arcana"),
            Map.entry(59, "8 of Cups - Minor Arcana (Reversed)"),
            Map.entry(60, "9 of Cups - Minor Arcana"),
            Map.entry(61, "9 of Cups - Minor Arcana (Reversed)"),
            Map.entry(62, "10 of Cups - Minor Arcana"),
            Map.entry(63, "10 of Cups - Minor Arcana (Reversed)"),
            Map.entry(64, "Page of Cups - Minor Arcana"),
            Map.entry(65, "Page of Cups - Minor Arcana (Reversed)"),
            Map.entry(66, "Knight of Cups - Minor Arcana"),
            Map.entry(67, "Knight of Cups - Minor Arcana (Reversed)"),
            Map.entry(68, "Queen of Cups - Minor Arcana"),
            Map.entry(69, "Queen of Cups - Minor Arcana (Reversed)"),
            Map.entry(70, "King of Cups - Minor Arcana"),
            Map.entry(71, "King of Cups - Minor Arcana (Reversed)"),

            // Minor Arcana - Wands
            Map.entry(72, "Ace of Wands - Minor Arcana"),
            Map.entry(73, "Ace of Wands - Minor Arcana (Reversed)"),
            Map.entry(74, "2 of Wands - Minor Arcana"),
            Map.entry(75, "2 of Wands - Minor Arcana (Reversed)"),
            Map.entry(76, "3 of Wands - Minor Arcana"),
            Map.entry(77, "3 of Wands - Minor Arcana (Reversed)"),
            Map.entry(78, "4 of Wands - Minor Arcana"),
            Map.entry(79, "4 of Wands - Minor Arcana (Reversed)"),
            Map.entry(80, "5 of Wands - Minor Arcana"),
            Map.entry(81, "5 of Wands - Minor Arcana (Reversed)"),
            Map.entry(82, "6 of Wands - Minor Arcana"),
            Map.entry(83, "6 of Wands - Minor Arcana (Reversed)"),
            Map.entry(84, "7 of Wands - Minor Arcana"),
            Map.entry(85, "7 of Wands - Minor Arcana (Reversed)"),
            Map.entry(86, "8 of Wands - Minor Arcana"),
            Map.entry(87, "8 of Wands - Minor Arcana (Reversed)"),
            Map.entry(88, "9 of Wands - Minor Arcana"),
            Map.entry(89, "9 of Wands - Minor Arcana (Reversed)"),
            Map.entry(90, "10 of Wands - Minor Arcana"),
            Map.entry(91, "10 of Wands - Minor Arcana (Reversed)"),
            Map.entry(92, "Page of Wands - Minor Arcana"),
            Map.entry(93, "Page of Wands - Minor Arcana (Reversed)"),
            Map.entry(94, "Knight of Wands - Minor Arcana"),
            Map.entry(95, "Knight of Wands - Minor Arcana (Reversed)"),
            Map.entry(96, "Queen of Wands - Minor Arcana"),
            Map.entry(97, "Queen of Wands - Minor Arcana (Reversed)"),
            Map.entry(98, "King of Wands - Minor Arcana"),
            Map.entry(99, "King of Wands - Minor Arcana (Reversed)"),

            // Minor Arcana - Swords
            Map.entry(100, "Ace of Swords - Minor Arcana"),
            Map.entry(101, "Ace of Swords - Minor Arcana (Reversed)"),
            Map.entry(102, "2 of Swords - Minor Arcana"),
            Map.entry(103, "2 of Swords - Minor Arcana (Reversed)"),
            Map.entry(104, "3 of Swords - Minor Arcana"),
            Map.entry(105, "3 of Swords - Minor Arcana (Reversed)"),
            Map.entry(106, "4 of Swords - Minor Arcana"),
            Map.entry(107, "4 of Swords - Minor Arcana (Reversed)"),
            Map.entry(108, "5 of Swords - Minor Arcana"),
            Map.entry(109, "5 of Swords - Minor Arcana (Reversed)"),
            Map.entry(110, "6 of Swords - Minor Arcana"),
            Map.entry(111, "6 of Swords - Minor Arcana (Reversed)"),
            Map.entry(112, "7 of Swords - Minor Arcana"),
            Map.entry(113, "7 of Swords - Minor Arcana (Reversed)"),
            Map.entry(114, "8 of Swords - Minor Arcana"),
            Map.entry(115, "8 of Swords - Minor Arcana (Reversed)"),
            Map.entry(116, "9 of Swords - Minor Arcana"),
            Map.entry(117, "9 of Swords - Minor Arcana (Reversed)"),
            Map.entry(118, "10 of Swords - Minor Arcana"),
            Map.entry(119, "10 of Swords - Minor Arcana (Reversed)"),
            Map.entry(120, "Page of Swords - Minor Arcana"),
            Map.entry(121, "Page of Swords - Minor Arcana (Reversed)"),
            Map.entry(122, "Knight of Swords - Minor Arcana"),
            Map.entry(123, "Knight of Swords - Minor Arcana (Reversed)"),
            Map.entry(124, "Queen of Swords - Minor Arcana"),
            Map.entry(125, "Queen of Swords - Minor Arcana (Reversed)"),
            Map.entry(126, "King of Swords - Minor Arcana"),
            Map.entry(127, "King of Swords - Minor Arcana (Reversed)"),

            // Minor Arcana - Pentacles
            Map.entry(128, "Ace of Pentacles - Minor Arcana"),
            Map.entry(129, "Ace of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(130, "2 of Pentacles - Minor Arcana"),
            Map.entry(131, "2 of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(132, "3 of Pentacles - Minor Arcana"),
            Map.entry(133, "3 of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(134, "4 of Pentacles - Minor Arcana"),
            Map.entry(135, "4 of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(136, "5 of Pentacles - Minor Arcana"),
            Map.entry(137, "5 of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(138, "6 of Pentacles - Minor Arcana"),
            Map.entry(139, "6 of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(140, "7 of Pentacles - Minor Arcana"),
            Map.entry(141, "7 of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(142, "8 of Pentacles - Minor Arcana"),
            Map.entry(143, "8 of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(144, "9 of Pentacles - Minor Arcana"),
            Map.entry(145, "9 of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(146, "10 of Pentacles - Minor Arcana"),
            Map.entry(147, "10 of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(148, "Page of Pentacles - Minor Arcana"),
            Map.entry(149, "Page of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(150, "Knight of Pentacles - Minor Arcana"),
            Map.entry(151, "Knight of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(152, "Queen of Pentacles - Minor Arcana"),
            Map.entry(153, "Queen of Pentacles - Minor Arcana (Reversed)"),
            Map.entry(154, "King of Pentacles - Minor Arcana"),
            Map.entry(155, "King of Pentacles - Minor Arcana (Reversed)")
    );

    public Map<Integer, String> getCards() {
        return cards;
    }

}
